/**
 * Synthetic mock product catalog — clearly not real Odoo/pricing data.
 * Supports eligibility testing across portfolio, restrictions, and Mesoestetic guard.
 */

import { createHash } from "node:crypto";
import type { NuviorProduct } from "@/domain/products/nuviorProduct";
import { CATALOG_PRODUCT_IDS } from "@/domain/products/leadProductCompat";

const MOCK_SOURCE_UPDATED = "2026-09-01T12:00:00.000Z";

export { MOCK_SOURCE_UPDATED };

export const MOCK_CATALOG_FIXTURES: NuviorProduct[] = [
  {
    id: CATALOG_PRODUCT_IDS.APTOS,
    externalId: "MOCK-ODOO-1001",
    sku: "SYN-APTOS-CORE",
    name: "Aptos Thread Lifting (Synthetic)",
    brand: "Aptos",
    productFamily: "APTOS",
    active: true,
    sellable: true,
    availabilityStatus: "AVAILABLE",
    capabilityTags: ["THREAD_LIFTING"],
    applicableSegments: [1],
    relevantServices: ["thread lift", "PDO threads", "non-surgical facelift"],
    practitionerRequirements: ["INJECTION_SCOPE", "PHYSICIAN_NP_OR_ELIGIBLE_RN"],
    provinceRestrictions: [],
    trainingRequired: false,
    certificationPathway: "NONE",
    approvedPositioning:
      "Bioabsorbable lifting threads for physician-led aesthetic clinics. Requires injection scope.",
    commercialPriority: 90,
    recommendable: true,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: CATALOG_PRODUCT_IDS.APTOS_3_LEVEL_CERTIFICATION,
    externalId: "MOCK-ODOO-1002",
    sku: "SYN-APTOS-CERT-3",
    name: "Aptos 3-Level Certification Pathway (Synthetic)",
    brand: "Aptos",
    productFamily: "APTOS",
    active: true,
    sellable: true,
    availabilityStatus: "AVAILABLE",
    capabilityTags: ["THREAD_LIFTING", "TRAINING_CERTIFICATION"],
    applicableSegments: [1],
    relevantServices: ["Aptos certification", "physician training"],
    practitionerRequirements: ["PHYSICIAN_OR_NP"],
    provinceRestrictions: [],
    trainingRequired: true,
    certificationPathway: "THREE_LEVEL",
    approvedPositioning: "Certification pathway for physicians and NPs.",
    commercialPriority: 70,
    recommendable: true,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: CATALOG_PRODUCT_IDS.APTOS_4_LEVEL_CERTIFICATION,
    externalId: "MOCK-ODOO-1003",
    sku: "SYN-APTOS-CERT-4",
    name: "Aptos 4-Level Certification Pathway (Synthetic)",
    brand: "Aptos",
    productFamily: "APTOS",
    active: true,
    sellable: true,
    availabilityStatus: "AVAILABLE",
    capabilityTags: ["THREAD_LIFTING", "TRAINING_CERTIFICATION"],
    applicableSegments: [1],
    relevantServices: ["Aptos certification", "RN/IMG/ND training"],
    practitionerRequirements: ["PHYSICIAN_NP_OR_ELIGIBLE_RN"],
    provinceRestrictions: [],
    trainingRequired: true,
    certificationPathway: "FOUR_LEVEL",
    approvedPositioning: "Extended certification pathway where provincial scope allows.",
    commercialPriority: 65,
    recommendable: true,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: "nuvior-aptos-legacy-kit",
    externalId: "MOCK-ODOO-1099",
    sku: "SYN-APTOS-LEGACY",
    name: "Aptos Legacy Starter Kit (Synthetic — Inactive)",
    brand: "Aptos",
    productFamily: "APTOS",
    active: false,
    sellable: false,
    availabilityStatus: "DISCONTINUED",
    capabilityTags: ["THREAD_LIFTING"],
    applicableSegments: [1],
    relevantServices: [],
    practitionerRequirements: ["INJECTION_SCOPE"],
    provinceRestrictions: [],
    trainingRequired: false,
    certificationPathway: "NONE",
    approvedPositioning: null,
    commercialPriority: null,
    recommendable: false,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: CATALOG_PRODUCT_IDS.DERMACEUTIC,
    externalId: "MOCK-ODOO-2001",
    sku: "SYN-DERM-PRO",
    name: "Dermaceutic Professional Line (Synthetic)",
    brand: "Dermaceutic",
    productFamily: "DERMACEUTIC",
    active: true,
    sellable: true,
    availabilityStatus: "AVAILABLE",
    capabilityTags: [
      "PROFESSIONAL_PEEL",
      "PIGMENTATION_CORRECTION",
      "ACNE_PROTOCOL",
      "MEDICAL_GRADE_SKINCARE",
    ],
    applicableSegments: [1, 3, 4],
    relevantServices: ["chemical peel", "corrective skincare", "pigmentation", "acne protocol"],
    practitionerRequirements: ["NONE"],
    provinceRestrictions: [],
    trainingRequired: false,
    certificationPathway: "NONE",
    approvedPositioning: "Clinical peels and cosmeceuticals for professional skincare workflows.",
    commercialPriority: 85,
    recommendable: true,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: CATALOG_PRODUCT_IDS.FIDIA_HY_TISSUE_PRP,
    externalId: "MOCK-ODOO-3001",
    sku: "SYN-FIDIA-PRP",
    name: "Fidia Hy-tissue PRP (Synthetic)",
    brand: "Fidia",
    productFamily: "FIDIA_HY_TISSUE_PRP",
    active: true,
    sellable: true,
    availabilityStatus: "AVAILABLE",
    capabilityTags: ["PRP_HAIR", "PRP_REGENERATIVE"],
    applicableSegments: [1, 2],
    relevantServices: ["PRP facial", "PRP hair", "regenerative injection"],
    practitionerRequirements: ["INJECTION_SCOPE"],
    provinceRestrictions: [],
    trainingRequired: false,
    certificationPathway: "NONE",
    approvedPositioning: "Hy-tissue PRP for clinics with blood-draw and injection scope.",
    commercialPriority: 75,
    recommendable: true,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: "nuvior-fidia-restricted-demo",
    externalId: "MOCK-ODOO-3002",
    sku: "SYN-FIDIA-QC-DEMO",
    name: "Fidia PRP Demo — QC Restricted (Synthetic)",
    brand: "Fidia",
    productFamily: "FIDIA_HY_TISSUE_PRP",
    active: true,
    sellable: true,
    availabilityStatus: "LIMITED",
    capabilityTags: ["PRP_REGENERATIVE"],
    applicableSegments: [2],
    relevantServices: ["PRP demo"],
    practitionerRequirements: ["INJECTION_SCOPE"],
    provinceRestrictions: ["QC"],
    trainingRequired: true,
    certificationPathway: "NONE",
    approvedPositioning: "Synthetic fixture for province restriction testing.",
    commercialPriority: 10,
    recommendable: true,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: CATALOG_PRODUCT_IDS.GESKE,
    externalId: "MOCK-ODOO-4001",
    sku: "SYN-GESKE-RETAIL",
    name: "GESKE At-Home Devices (Synthetic)",
    brand: "GESKE",
    productFamily: "GESKE",
    active: true,
    sellable: true,
    availabilityStatus: "AVAILABLE",
    capabilityTags: ["RETAIL_BEAUTY_DEVICE"],
    applicableSegments: [5, 6],
    relevantServices: ["retail beauty device", "at-home skincare tools"],
    practitionerRequirements: ["NONE"],
    provinceRestrictions: [],
    trainingRequired: false,
    certificationPathway: "NONE",
    approvedPositioning: "Retail beauty devices for spa and boutique channels.",
    commercialPriority: 50,
    recommendable: true,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: "nuvior-geske-wholesale-only",
    externalId: "MOCK-ODOO-4002",
    sku: "SYN-GESKE-B2B",
    name: "GESKE Wholesale Bundle (Synthetic — Not Sellable)",
    brand: "GESKE",
    productFamily: "GESKE",
    active: true,
    sellable: false,
    availabilityStatus: "OUT_OF_STOCK",
    capabilityTags: ["RETAIL_BEAUTY_DEVICE"],
    applicableSegments: [5],
    relevantServices: [],
    practitionerRequirements: ["NONE"],
    provinceRestrictions: [],
    trainingRequired: false,
    certificationPathway: "NONE",
    approvedPositioning: null,
    commercialPriority: null,
    recommendable: false,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
  {
    id: CATALOG_PRODUCT_IDS.MESOESTETIC_HISTORICAL,
    externalId: "MOCK-ODOO-5001",
    sku: "SYN-MESO-HIST",
    name: "Mesoestetic Historical Stock (Synthetic — Non-Recommendable)",
    brand: "Mesoestetic",
    productFamily: "MESOESTETIC",
    active: false,
    sellable: false,
    availabilityStatus: "LIMITED",
    capabilityTags: ["MEDICAL_GRADE_SKINCARE", "PIGMENTATION_CORRECTION"],
    applicableSegments: [3, 4],
    relevantServices: ["historical stock only"],
    practitionerRequirements: ["NONE"],
    provinceRestrictions: [],
    trainingRequired: false,
    certificationPathway: "NONE",
    approvedPositioning:
      "Historical distributor stock only — not an ongoing NUVIOR line. Retention via Dermaceutic.",
    commercialPriority: null,
    recommendable: false,
    source: "mock",
    sourceUpdatedAt: MOCK_SOURCE_UPDATED,
  },
];

export function computeMockCatalogVersion(products: NuviorProduct[]): string {
  const payload = products
    .map((p) => `${p.id}:${p.active}:${p.sellable}:${p.sourceUpdatedAt}`)
    .sort()
    .join("|");
  return createHash("sha256").update(payload).digest("hex").slice(0, 16);
}

export const MOCK_CATALOG_VERSION = computeMockCatalogVersion(MOCK_CATALOG_FIXTURES);
