import type { GeoPoint } from "@/domain/geo";
import type { RawPlace } from "./types";
import { emptyProvenance, unknownContact } from "./types";

/**
 * Synthetic fixtures for engineering only — not real clinics.
 * Classification comes from names/types via domain classifier.
 */

export const MOCK_GEOCODES: Record<string, GeoPoint> = {
  "ON|M5V 2T6": { lat: 43.6426, lng: -79.3871 },
  "ON|M5V2T6": { lat: 43.6426, lng: -79.3871 },
  "ON|TORONTO": { lat: 43.6532, lng: -79.3832 },
  "ON|100 QUEEN ST W, TORONTO": { lat: 43.6532, lng: -79.3832 },
  "AB|T2P 1J9": { lat: 51.0447, lng: -114.0719 },
  "AB|T2P1J9": { lat: 51.0447, lng: -114.0719 },
  "AB|CALGARY": { lat: 51.0447, lng: -114.0719 },
  "BC|V6B 1A1": { lat: 49.2827, lng: -123.1207 },
  "BC|V6B1A1": { lat: 49.2827, lng: -123.1207 },
  "BC|VANCOUVER": { lat: 49.2827, lng: -123.1207 },
};

function mockPlace(
  partial: Omit<RawPlace, "provider" | "fetchedAt" | "fieldProvenance" | "mainPhone" | "openingHoursJson" | "unitSuite" | "googleMapsUrl" | "website"> &
    Partial<Pick<RawPlace, "mainPhone" | "openingHoursJson" | "unitSuite" | "googleMapsUrl" | "website">>,
): RawPlace {
  const fetchedAt = new Date().toISOString();
  const base: RawPlace = {
    unitSuite: null,
    googleMapsUrl: null,
    website: null,
    mainPhone: unknownContact(),
    openingHoursJson: null,
    provider: "mock",
    fetchedAt,
    fieldProvenance: {},
    ...partial,
  };
  const prov = emptyProvenance("mock", base.placeId, true);
  base.fieldProvenance = {
    businessName: prov,
    streetAddress: prov,
    latitude: { ...prov, needsVerification: false, confidence: "high" },
    longitude: { ...prov, needsVerification: false, confidence: "high" },
  };
  return base;
}

export const MOCK_PLACES: RawPlace[] = [
  mockPlace({
    placeId: "mock-on-001",
    businessName: "Mock Yorkville Dermatology",
    streetAddress: "MOCK 120 Bloor St W",
    unitSuite: "Suite 200",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5S 1N4",
    latitude: 43.6695,
    longitude: -79.3948,
    googleRating: 4.7,
    googleReviewCount: 128,
    googleTypes: ["dermatologist", "doctor"],
    primaryType: "dermatologist",
    discoverySignals: ["Dermaceutic", "Aptos threads"],
  }),
  mockPlace({
    placeId: "mock-on-002",
    businessName: "Mock King West Cosmetic Medicine",
    streetAddress: "MOCK 560 King St W",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5V 1M3",
    latitude: 43.6446,
    longitude: -79.3995,
    googleRating: 4.5,
    googleReviewCount: 86,
    googleTypes: ["doctor", "health"],
    primaryType: "doctor",
    discoverySignals: ["Aptos threads"],
  }),
  mockPlace({
    placeId: "mock-on-003",
    businessName: "Mock Harbourfront NP Injectables",
    streetAddress: "MOCK 225 Queens Quay W",
    unitSuite: "Unit 4",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5J 2X1",
    latitude: 43.6383,
    longitude: -79.3817,
    googleRating: 4.8,
    googleReviewCount: 54,
    googleTypes: ["doctor"],
    primaryType: "doctor",
    discoverySignals: ["Aptos threads"],
  }),
  mockPlace({
    placeId: "mock-on-004",
    businessName: "Mock Liberty Sports Medicine",
    streetAddress: "MOCK 171 East Liberty St",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M6K 3P6",
    latitude: 43.6389,
    longitude: -79.4132,
    googleRating: 4.3,
    googleReviewCount: 41,
    googleTypes: ["physiotherapist", "doctor"],
    primaryType: "doctor",
    discoverySignals: ["Fidia Hy-tissue PRP"],
  }),
  mockPlace({
    placeId: "mock-on-005",
    businessName: "Mock Queen West MedSpa",
    streetAddress: "MOCK 650 Queen St W",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M6J 1E5",
    latitude: 43.6472,
    longitude: -79.4091,
    googleRating: 4.6,
    googleReviewCount: 210,
    googleTypes: ["spa", "beauty_salon"],
    primaryType: "spa",
    discoverySignals: ["Taxonomy clinic"],
  }),
  mockPlace({
    placeId: "mock-on-006",
    businessName: "Mock RN Injector Studio Annex",
    streetAddress: "MOCK 480 Bloor St W",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5S 1X8",
    latitude: 43.6658,
    longitude: -79.4102,
    googleRating: 4.9,
    googleReviewCount: 73,
    googleTypes: ["beauty_salon"],
    primaryType: "beauty_salon",
    discoverySignals: ["Aptos threads"],
  }),
  mockPlace({
    placeId: "mock-on-007",
    businessName: "Mock Pigment Lab Skin Studio",
    streetAddress: "MOCK 790 Dundas St W",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M6J 1V1",
    latitude: 43.6521,
    longitude: -79.4088,
    googleRating: 4.4,
    googleReviewCount: 39,
    googleTypes: ["beauty_salon"],
    primaryType: "beauty_salon",
    discoverySignals: ["Mesoestetic", "Dermaceutic"],
  }),
  mockPlace({
    placeId: "mock-on-008",
    businessName: "Mock Distillery Day Spa",
    streetAddress: "MOCK 55 Mill St",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5A 3C4",
    latitude: 43.6503,
    longitude: -79.3595,
    googleRating: 4.2,
    googleReviewCount: 160,
    googleTypes: ["spa"],
    primaryType: "spa",
    discoverySignals: ["GESKE"],
  }),
  mockPlace({
    placeId: "mock-on-009",
    businessName: "Mock Clean Beauty Boutique Yorkville",
    streetAddress: "MOCK 87 Avenue Rd",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5R 2G3",
    latitude: 43.6712,
    longitude: -79.3941,
    googleRating: 4.1,
    googleReviewCount: 22,
    googleTypes: ["store"],
    primaryType: "store",
    discoverySignals: ["GESKE"],
  }),
  mockPlace({
    placeId: "mock-on-010",
    businessName: "Mock Midtown Hair Restoration",
    streetAddress: "MOCK 2300 Yonge St",
    unitSuite: "Suite 500",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M4P 1E4",
    latitude: 43.7076,
    longitude: -79.3987,
    googleRating: 4.6,
    googleReviewCount: 95,
    googleTypes: ["doctor"],
    primaryType: "doctor",
    discoverySignals: ["Fidia Hy-tissue PRP", "Taxonomy clinic"],
  }),
  mockPlace({
    placeId: "mock-on-011",
    businessName: "Mock Do-Not-Contact Demo Clinic",
    streetAddress: "MOCK 1 Test DNC Ave",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5V 0A1",
    latitude: 43.645,
    longitude: -79.39,
    googleRating: null,
    googleReviewCount: null,
    googleTypes: ["plastic surgery clinic", "doctor"],
    primaryType: "doctor",
    discoverySignals: ["Taxonomy clinic"],
  }),
  mockPlace({
    placeId: "mock-on-012",
    businessName: "Mock Former Mesoestetic Skin Lab",
    streetAddress: "MOCK 33 Elm St",
    city: "Toronto",
    provinceCode: "ON",
    postalCode: "M5G 1H1",
    latitude: 43.6575,
    longitude: -79.3832,
    googleRating: 4.5,
    googleReviewCount: 67,
    googleTypes: ["spa", "skin clinic"],
    primaryType: "spa",
    discoverySignals: ["Mesoestetic", "Dermaceutic"],
  }),
  mockPlace({
    placeId: "mock-ab-001",
    businessName: "Mock Kensington Cosmetic MD",
    streetAddress: "MOCK 1124 Kensington Rd NW",
    city: "Calgary",
    provinceCode: "AB",
    postalCode: "T2N 3P3",
    latitude: 51.0524,
    longitude: -114.1109,
    googleRating: 4.7,
    googleReviewCount: 88,
    googleTypes: ["doctor"],
    primaryType: "doctor",
    discoverySignals: ["Aptos threads"],
  }),
  mockPlace({
    placeId: "mock-ab-002",
    businessName: "Mock Beltline Sports Injury",
    streetAddress: "MOCK 1400 10 Ave SW",
    city: "Calgary",
    provinceCode: "AB",
    postalCode: "T3C 0J4",
    latitude: 51.0431,
    longitude: -114.092,
    googleRating: 4.4,
    googleReviewCount: 50,
    googleTypes: ["doctor"],
    primaryType: "doctor",
    discoverySignals: ["Fidia Hy-tissue PRP"],
  }),
  mockPlace({
    placeId: "mock-ab-003",
    businessName: "Mock Eau Claire MedSpa",
    streetAddress: "MOCK 200 Barclay Parade SW",
    city: "Calgary",
    provinceCode: "AB",
    postalCode: "T2P 4R5",
    latitude: 51.052,
    longitude: -114.068,
    googleRating: 4.6,
    googleReviewCount: 140,
    googleTypes: ["spa"],
    primaryType: "spa",
    discoverySignals: ["Taxonomy clinic"],
  }),
  mockPlace({
    placeId: "mock-bc-001",
    businessName: "Mock Yaletown ND Aesthetics",
    streetAddress: "MOCK 1080 Mainland St",
    city: "Vancouver",
    provinceCode: "BC",
    postalCode: "V6B 2T4",
    latitude: 49.2755,
    longitude: -123.1205,
    googleRating: 4.5,
    googleReviewCount: 33,
    googleTypes: ["naturopathic"],
    primaryType: "health",
    discoverySignals: ["Taxonomy clinic"],
  }),
  mockPlace({
    placeId: "mock-bc-002",
    businessName: "Mock Coal Harbour Plastic Surgery",
    streetAddress: "MOCK 555 W Cordova St",
    unitSuite: "Floor 3",
    city: "Vancouver",
    provinceCode: "BC",
    postalCode: "V6B 1G1",
    latitude: 49.2856,
    longitude: -123.1126,
    googleRating: 4.9,
    googleReviewCount: 201,
    googleTypes: ["plastic_surgery_clinic", "doctor"],
    primaryType: "doctor",
    discoverySignals: ["Aptos threads", "Taxonomy clinic"],
  }),
];
